GET http://localhost:5000/users

###
POST http://localhost:5000/add-users
Content-Type: application/json

{
    "name": "faizOnCloud2",
    "email": "faizmelayanglayang2@gmail.com",
    "gender": "sarden kaleng"
}

###
PATCH http://localhost:5000/user/2
Content-Type: application/json

{
    "name": "faizzz",
    "email": "effendi@gmail.com"
}

###
DELETE http://localhost:5000/user/7